### ISSUE TITLE
Wrong copyright holder

### ISSUE THREAD

**Issue by PhilippIRL** [AdriDevelopsThings/strecken-info-rs#8]
https://github.com/AdriDevelopsThings/strecken-info-rs/blob/40c7e57f8457e70258cda89b8754d61c2c727634/LICENSE-APACHE#LL3C32-L3C32

**Comment by AdriDevelopsThings** [comment]
I don't know what you are talking about: https://github.com/AdriDevelopsThings/strecken-info-rs/blob/main/LICENSE-APACHE#L3 /s

But thanks for submitting this issue, I fixed it :3
